### ISSUE TITLE
Starting the websocket server fails due to permission errors

### ISSUE THREAD

**Issue by TheZXCVQ** [benediktwerner/lichess-docker#5]
Hi!
I've been trying to get this running. When running `sbt run` inside `docker exec` i get permission denied errors.
The following code works only if the UID of the user running docker is 1000. Otherwise future commands fail with permission denied errors.
https://github.com/benediktwerner/lichess-docker/blob/d6cd401135fa72064d8ce26231fdfd200a8a0fa8/README.md?plain=1#L15

Could you clarify the documentation on how to ensure the UID's match?

**Comment by benediktwerner** [comment]
Not sure what the best/proper way to do this is but I guess you can add `-u <userid>` to https://github.com/benediktwerner/lichess-docker/blob/master/Dockerfile/#L5 where `<userid>` is the id of the user owning the directory on the docker host (which you can find out by running `id` as that user).

In general, I'd currently recommend https://github.com/lichess-org/lila-gitpod for an easy Lichess Dev setup to get started though.
